#!/usr/bin/env bash

echo "Applying migrations"

cargo sqlx database create --database-url "${ROBSERVER_PG_ADDR}" && echo "DB created" || echo "DB creation failed"
cargo sqlx migrate run --database-url "${ROBSERVER_PG_ADDR}"
