name: 'Test'

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: rustup toolchain list
    - run: cargo --version

    - name: Run tests
      run: cargo test

    - name: Run clippy
      run: cargo clippy

    - name: Run fmt
      run: cargo fmt --check
