name: 'Test'

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - run: rustup toolchain list
    - run: cargo --version

    - name: Run tests
      run: cargo test

    - name: Run clippy
      run: cargo clippy

    - name: Run fmt
      run: cargo fmt --check
